// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Respose struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 []*User  `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respose) Reset()         { *m = Respose{} }
func (m *Respose) String() string { return proto.CompactTextString(m) }
func (*Respose) ProtoMessage()    {}
func (*Respose) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Respose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respose.Unmarshal(m, b)
}
func (m *Respose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respose.Marshal(b, m, deterministic)
}
func (m *Respose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respose.Merge(m, src)
}
func (m *Respose) XXX_Size() int {
	return xxx_messageInfo_Respose.Size(m)
}
func (m *Respose) XXX_DiscardUnknown() {
	xxx_messageInfo_Respose.DiscardUnknown(m)
}

var xxx_messageInfo_Respose proto.InternalMessageInfo

func (m *Respose) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Respose) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Respose) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

type Respose2 struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respose2) Reset()         { *m = Respose2{} }
func (m *Respose2) String() string { return proto.CompactTextString(m) }
func (*Respose2) ProtoMessage()    {}
func (*Respose2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *Respose2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respose2.Unmarshal(m, b)
}
func (m *Respose2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respose2.Marshal(b, m, deterministic)
}
func (m *Respose2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respose2.Merge(m, src)
}
func (m *Respose2) XXX_Size() int {
	return xxx_messageInfo_Respose2.Size(m)
}
func (m *Respose2) XXX_DiscardUnknown() {
	xxx_messageInfo_Respose2.DiscardUnknown(m)
}

var xxx_messageInfo_Respose2 proto.InternalMessageInfo

func (m *Respose2) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Respose2) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Respose2) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "protos.Request")
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*Respose)(nil), "protos.Respose")
	proto.RegisterType((*Respose2)(nil), "protos.Respose2")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	GetList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respose, error)
	GetOne(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respose2, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) GetList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respose, error) {
	out := new(Respose)
	err := c.cc.Invoke(ctx, "/protos.Test/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) GetOne(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Respose2, error) {
	out := new(Respose2)
	err := c.cc.Invoke(ctx, "/protos.Test/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	GetList(context.Context, *Request) (*Respose, error)
	GetOne(context.Context, *Request) (*Respose2, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Test/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).GetList(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Test/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).GetOne(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _Test_GetList_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _Test_GetOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x31, 0x4f, 0xc4, 0x30,
	0x0c, 0x85, 0xaf, 0x4d, 0x74, 0x77, 0x18, 0x04, 0x27, 0x4f, 0x85, 0xa9, 0xca, 0x74, 0x42, 0x6a,
	0x87, 0x30, 0xb2, 0x01, 0x52, 0x17, 0x10, 0x22, 0x82, 0x85, 0xad, 0x28, 0x16, 0xea, 0x40, 0x53,
	0x6a, 0xf3, 0xff, 0x51, 0xd2, 0x22, 0xa1, 0xc2, 0x72, 0x53, 0x9e, 0x9e, 0x9f, 0x3f, 0xc7, 0x06,
	0x10, 0x62, 0xa9, 0x87, 0x31, 0x48, 0xc0, 0x75, 0x7a, 0xd8, 0x9c, 0xc3, 0xc6, 0xd1, 0xe7, 0x17,
	0xb1, 0xe0, 0x29, 0xe4, 0x9d, 0x2f, 0xb2, 0x32, 0xdb, 0x1f, 0xb9, 0xbc, 0xf3, 0xe6, 0x12, 0xf4,
	0x0b, 0xd3, 0xb8, 0xf4, 0x11, 0x41, 0xf7, 0xed, 0x07, 0x15, 0x79, 0x72, 0x92, 0x36, 0x4f, 0x11,
	0xc3, 0x43, 0x60, 0x8a, 0xe5, 0xdb, 0xe0, 0x29, 0x35, 0x28, 0x97, 0x34, 0xee, 0x40, 0x3d, 0xf0,
	0xfb, 0xdc, 0x11, 0x25, 0x96, 0xa0, 0xef, 0x5a, 0x69, 0x0b, 0x55, 0xaa, 0xfd, 0xb1, 0x3d, 0x99,
	0x7e, 0xc5, 0x75, 0x1c, 0xe8, 0x52, 0xc5, 0x38, 0xd8, 0xce, 0x48, 0x7b, 0x30, 0x33, 0xfb, 0x9f,
	0x69, 0x3d, 0xe8, 0xe7, 0xb8, 0x6a, 0x05, 0x9b, 0x86, 0xe4, 0xbe, 0x63, 0xc1, 0xb3, 0x9f, 0xd8,
	0x7c, 0x86, 0x8b, 0x5f, 0x46, 0x9a, 0x6e, 0x56, 0x58, 0xc1, 0xba, 0x21, 0x79, 0xec, 0xe9, 0x6f,
	0x7a, 0xb7, 0x48, 0x5b, 0xb3, 0xba, 0x81, 0xd7, 0x6d, 0x7d, 0x3d, 0xd9, 0x6f, 0xd3, 0x9d, 0xaf,
	0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x62, 0xda, 0x4f, 0x4c, 0x7c, 0x01, 0x00, 0x00,
}
